### ISSUE TITLE
Consider End Dates for Personal Events

### ISSUE THREAD

**Issue by snugthejoiner** [snugthejoiner/theusthread#17]
May want to stick to start date (aka Date) for PersonalEvents. Maybe consider end dates as a future feature.

**Comment by snugthejoiner** [comment]
@Brit200313 FYI, I'm using the Github **issues** feature. Not @ing you on them. Except now.

**Comment by Brit200313** [comment]
I get them all since I'm following the repo. Don't worry about it, I like to see you think.
