### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by snugthejoiner** [snugthejoiner/theusthread#23]

**Comment by snugthejoiner** [comment]
Alright. My thought is that tags will be broad categories used for HistoricalEvents, but which people can use for PersonalEvents. *Military, Economic, ETC*

If I were to have it so people could **create** their own tags, it would be a much larger project. What are your thoughts?

For the time being, I picture choosing from existing tags (apple, potato,orange) on every PersonalEvent#edit screen.

I added this to **edit.html.erb**
`<%= render :partial => '/tags/taglist.html.erb' %>
`
and I currently have this for my method of selecting from existing tags

```
<% Tag.select("Distinct name").each do |tag| %>
<%= link_to tag.name, tags_path(id: @personal_event.id), method: :create %>
<% end %>
```

I think I'll push to this branch while I wrestle with it.

**Comment by Brit200313** [comment]
I had an easy time with have people generate their own tags with the acts_as_tagable gem. I'm certainly happy to help you set that up. 

Otherwise, you can install rails_admin and generate the tags from there as an admin user. I think trying out the collection_select helper with it could also be an interesting choice.

**Comment by snugthejoiner** [comment]
So, I seem to have the same problem on every project. I can't seem to get the solution through my head.

I'm on the personal_events/edit.html.erb page (so obviously the PE controller) and my params are
`"person_id"=>"11", "controller"=>"personal_events", "action"=>"edit", "id"=>"19"`

I put my 'taglist' partial in that page, which references `tags/_taglist.html.erb'

To create a new tag record I need the name (chosen from pre-existing values for now at least), the `tagable_id` which is the `id` of the personal_event (and historical_event.id for Historical) and the `tagable_type` is `personal`.

**SO**, my main problem is: how do I get the `personal_event.id` (19) to the `tag_controller#create` function?! It's so basic, but I still struggle with it.

**Comment by Brit200313** [comment]
Putting these here for reference: 

Railscast => http://railscasts.com/episodes/196-nested-model-form-revised?view=comments
Cocoon => https://github.com/nathanvda/cocoon
Cocoon demo => https://github.com/nathanvda/cocoon_simple_form_demo

You got this! (but I'm here to help)

![popkey](http://d3htz3r28tzhqz.cloudfront.net/91WGnLLbaFgidSKVvzcH4ZgmT3s=/original-23be8c75-13e8-41c0-8a54-c4ea858e72db.gif/DoLRG.gif?c=desktop&l=search&f=.gif)

**Comment by snugthejoiner** [comment]
This seems done. I'll decide later whether to tweak **tags** in the view.
